version: '3.1'
services:
  webapp:
    build: .
    ports:
      - 9000:9000
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SS_twilio
