---
Name: myapp
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
    
# SilverStripe Dependency Injection
# See: https://docs.silverstripe.org/en/4/developer_guides/extending/injector/
# Subtitute 'SMSCryptoApp\Bitcoin\BlockcypherClient' for any other implementor of SMSCryptoApp\Bitcoin\ClientProvider
SilverStripe\Core\Injector\Injector:
  PaymentClient:
    class: 'SMSCryptoApp\API\BlockCypherClient'
    
PageController:
  dependencies: 
    paymentClient: '%$PaymentClient'
